apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: 2000nn/account-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-secrets
